#!/usr/bin/env bash
# Regenerates docs/decisions/index.md and docs/facts/index.md from the source
# files in those directories. Safe to re-run at any time — output is deterministic.
#
# Usage:
#   ./scripts/generate-knowledge-index.sh
#
# Invoked automatically by /plan-feature at the start of each run.
# Run manually after adding or editing any ADR or fact.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DECISIONS_DIR="$REPO_ROOT/docs/decisions"
FACTS_DIR="$REPO_ROOT/docs/facts"

# ── helpers ──────────────────────────────────────────────────────────────────

# First H1 heading in file (after optional front matter)
h1() {
  grep -m1 '^# ' "$1" | sed 's/^# //'
}

# Value of a YAML scalar or flow-sequence front-matter key, stripped of brackets
front_matter_value() {
  local key="$1" file="$2"
  awk -v key="$key" '
    /^---$/ { fm++; next }
    fm == 1 && $0 ~ "^"key":" {
      sub("^"key":[ \t]*", "")
      gsub(/[\[\]]/, "")
      print
      exit
    }
    fm >= 2 { exit }
  ' "$file" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

# First non-blank, non-heading paragraph line after front matter — truncated
summary() {
  awk '
    /^---$/ { fm++; next }
    fm < 2  { next }
    /^#/    { next }
    /^$/    { if (found) exit; next }
    { found=1; print; exit }
  ' "$1" | cut -c1-120 | sed "s/|/\\\\|/g"
}

# First non-blank line of a named section (## Section)
section_first_line() {
  local section="$1" file="$2"
  awk -v sec="$section" '
    /^## / { in_sec = ($0 == "## "sec); next }
    in_sec && /^$/ { next }
    in_sec && /^#/ { exit }
    in_sec { print; exit }
  ' "$file" | cut -c1-120 | sed "s/|/\\\\|/g"
}

# ── ADR index ─────────────────────────────────────────────────────────────────

generate_adr_index() {
  local out="$DECISIONS_DIR/index.md"

  {
    echo "<!-- generated by scripts/generate-knowledge-index.sh — do not edit by hand -->"
    echo ""
    echo "# ADR Index"
    echo ""
    echo "| ID | Title | Status | Summary |"
    echo "|----|-------|--------|---------|"

    for file in "$DECISIONS_DIR"/ADR-*.md; do
      [[ -f "$file" ]] || continue

      filename="$(basename "$file" .md)"
      id="${filename%%-*}-${filename#*-}"   # e.g. ADR-001
      # Re-derive: prefix before second hyphen
      id="$(echo "$filename" | grep -oE '^ADR-[0-9]+')"

      title="$(h1 "$file")"
      status="$(section_first_line "Status" "$file")"
      [[ -z "$status" ]] && status="—"
      smry="$(section_first_line "Context" "$file")"
      [[ -z "$smry" ]] && smry="$(section_first_line "Decision" "$file")"
      [[ -z "$smry" ]] && smry="$(summary "$file")"

      echo "| \`$id\` | $title | $status | $smry |"
    done
  } > "$out"

  local count
  count=$(grep -c '^| ' "$out" || true)
  count=$(( count > 1 ? count - 1 : 0 ))
  echo "  wrote $out ($count entries)"
}

# ── Facts index ───────────────────────────────────────────────────────────────

generate_facts_index() {
  local out="$FACTS_DIR/index.md"

  {
    echo "<!-- generated by scripts/generate-knowledge-index.sh — do not edit by hand -->"
    echo ""
    echo "# Facts Index"
    echo ""
    echo "| ID | Title | Topics | Summary |"
    echo "|----|-------|--------|---------|"

    for file in "$FACTS_DIR"/fact-*.md; do
      [[ -f "$file" ]] || continue

      filename="$(basename "$file" .md)"
      id="$(echo "$filename" | grep -oE '^fact-[0-9]+')"

      title="$(h1 "$file")"
      topics="$(front_matter_value "topics" "$file")"
      smry="$(summary "$file")"

      echo "| \`$id\` | $title | $topics | $smry |"
    done
  } > "$out"

  local count
  count=$(grep -c '^| ' "$out" || true)
  # subtract header row
  count=$(( count > 1 ? count - 1 : 0 ))
  echo "  wrote $out ($count entries)"
}

# ── main ──────────────────────────────────────────────────────────────────────

echo "Generating knowledge indexes…"

if [[ -d "$DECISIONS_DIR" ]]; then
  generate_adr_index
else
  echo "  skipping ADR index — $DECISIONS_DIR not found"
fi

if [[ -d "$FACTS_DIR" ]]; then
  generate_facts_index
else
  echo "  skipping facts index — $FACTS_DIR not found"
fi

echo "Done."
